### ISSUE TITLE
Cannot parse nested store struture like S3Store

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/jobflow#123]
The current yaml setup does not allow for S3Store to be parsed since it is just passing the full dictionary in as the kwarg to the constructor without constructing the index store first.

https://github.com/materialsproject/jobflow/blob/9ecf9efb70659bf472780ec2d3a59b718adc5cfc/src/jobflow/core/store.py#L661

```
JOB_STORE: 
    docs_store:
        type: MongoStore
        host: js.lbl.gov
        port: 30507
        database: js
        username: js
        collection_name: outputs
        password: xx
        mongoclient_kwargs:
            ssl : true
            tlsAllowInvalidCertificates: true
    additional_stores:
        data:
            type: S3Store
            index:
                type: MongoStore
                collection_name: outputs_blobs
                host: js.lbl.gov
                port: 30507
                database: js
                username: js
                password: xxxxx
                key: "job_id"
                mongoclient_kwargs:
                    ssl : true
                    tlsAllowInvalidCertificates: true
            bucket: "atomate-shen9"
            s3_profile: "lc-objstore"
            endpoint_url: "https://js.lbl.gov:443"
            key: "job_id"
```

Just putting a pin in this, for now, will fix it later this week.
