### ISSUE TITLE
BUG: Using an S3Store additional store in jobflow.yaml

### ISSUE THREAD

**Issue by arosen93** [materialsproject/jobflow#70]
I am trying to set up a MinIO bucket as an additional store in my `jobflow.yaml`. The format I have so far is below. However, this isn't sufficient because the `S3Store` takes an `index` as the first argument, which itself is a `MongoStore` pointing to the collection to use as an index for the data in S3/MinIO. Perhaps it's just not clear to me how to do this (in which case a docs update could help), but I don't think there is an easy way to have the `index` point to the `docs_store`.

```yaml
JOB_STORE:
    docs_store:
      type: MongoStore
      database: rosen_mp
      host: mongodb07.nersc.gov
      port: 27017
      username: <>
      password: <>
      collection_name: jobflow_outputs
    additional_stores:
      data:
        type: S3Store
        index: ??? # here is the issue. how to point to the above MongoStore
        bucket: rosen
        s3_profile:
          aws_access_key_id: <>
          aws_secret_access_key: <>
        compress: true
        endpoint_url: https://minio.materialsproject.org
        s3_workers: 24
```
